

# This file was *autogenerated* from the file ./sage_vrfinventaire.sage
from sage.all_cmdline import *   # import sage library

#!/usr/bin/env sage

import graphviz

f = graphviz.Digraph("G", filename="vpn-bgp-mpls.gv")
g=DiGraph()
f.attr("node", shape="circle")
g.add_vertex("pe1-clientA")
f.node("pe1-clientA")
g.add_edges([("pe1-clientA", "pe2-clientA")])
f.edge("pe1-clientA", "pe2-clientA", label="1")
g.add_edges([("pe2-clientA", "pe1-clientA")])
f.edge("pe2-clientA", "pe1-clientA", label="1")
g.add_vertex("pe2-clientA")
f.node("pe2-clientA")
g.add_vertex("pe1-clientB")
f.node("pe1-clientB")
g.add_vertex("pe1-clientC")
f.node("pe1-clientC")
g.add_vertex("pe1-clientD")
f.node("pe1-clientD")
g.add_edges([("pe1-clientD", "pe3-clientD")])
f.edge("pe1-clientD", "pe3-clientD", label="4")
g.add_edges([("pe3-clientD", "pe1-clientD")])
f.edge("pe3-clientD", "pe1-clientD", label="4")
g.add_vertex("pe3-clientD")
f.node("pe3-clientD")
g.add_vertex("pe1-clientE")
f.node("pe1-clientE")
g.add_edges([("pe1-clientE", "pe4-clientD")])
f.edge("pe1-clientE", "pe4-clientD", label="5")
g.add_edges([("pe4-clientD", "pe1-clientE")])
f.edge("pe4-clientD", "pe1-clientE", label="5")
g.add_vertex("pe4-clientD")
f.node("pe4-clientD")
g.add_edges([("pe1-clientE", "pe1-clientB")])
f.edge("pe1-clientE", "pe1-clientB", label="6")
g.add_edges([("pe1-clientE", "pe1-clientC")])
f.edge("pe1-clientE", "pe1-clientC", label="6")
g.add_edges([("pe1-clientB", "pe1-clientE")])
f.edge("pe1-clientB", "pe1-clientE", label="7")
g.add_edges([("pe1-clientC", "pe1-clientE")])
f.edge("pe1-clientC", "pe1-clientE", label="7")
g.show()
f.view()
g.connected_components()

