

# This file was *autogenerated* from the file ./vpn.sage
from sage.all_cmdline import *   # import sage library

#!/usr/bin/env sage

from sage.all import *

g=DiGraph()
g.add_edges([("A","B")]) 
g.add_vertex("C") 
g.show() 
p = g.plot()
g.save('/tmp/tmp.png') 
os.system('open /tmp/tmp.png')
g.connected_components()

